version: '3'

services:
  api:
    container_name: simple-api
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    volumes:
      - ./:/go/src/github.com/yoshikawataiki/simple-api
    ports:
      - 8080:8080
    tty:
      true
  db:
    image: mysql:latest
    container_name: simple-mysql
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306